[package]
authors = ["Nick Babcock <nbabcock19@hotmail.com>"]
license = "MIT"
name = "boxcars"
readme = "README.md"
edition = "2018"
repository = "https://github.com/nickbabcock/boxcars"
description = "Rocket league replay parser"
keywords = ["rocket-league"]
categories = ["parsing"]
version = "0.7.0-rc.1"
include = ["src/**/*.rs", "Cargo.toml", "build.rs"]

[dependencies]
serde = { version = "1", features = ["derive"] }
encoding_rs = "0.8"
byteorder = "1"
phf = { version = "0.8", features = ["macros"] }
fnv = "1.0"
if_chain = "1.0"
bitter = "0.4.0"
pyo3 = { version = "0.9.0-alpha.1", optional = true }
dict_derive = { version = "0.2.0", optional = true }

[features]
py = ["pyo3", "dict_derive"]

[dev-dependencies]
serde_json = "1"
criterion = "0.3"

[[bench]]
path = "benches/bench_boxcars.rs"
name = "bench_boxcars"
harness = false
